title: Bloggity Blog
description: Jekyll Blog

url: http://alifrumin.github.io/long-haul
baseurl: "/long-haul"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
# highlighter: pygments
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about.md
 - title: Contact
   url: /contact

social:
   github: alifrumin
   twitter: alifrumin
   facebook: alifrumin@yahoo.com
   email: alifrumin@gmail.com

# google_analytics: "UA-58263416-1"
